#server:
#  port: 8082
#
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3307/surveydb?serverTimezone=GMT%2b8
#    username: root
#    password: wryte
#
#mybatis-plus:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.surveysystemtext.entity


  server:
    port: 8080

  spring:
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/surveydb?serverdb=GMT%2b8
      username: root
      password: JGOWJIj01kG5mZpZ

  mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.surveysystemtext.entity